/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type AdminAccessSet = ContractEventLog<{
  _admin: string;
  _enabled: boolean;
  0: string;
  1: boolean;
}>;
export type ContractStatusSet = ContractEventLog<{
  _admin: string;
  _isActive: boolean;
  0: string;
  1: boolean;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type SaleAdded = ContractEventLog<{
  _nftId: string;
  _price: string;
  _owner: string;
  _timestamp: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type SaleCancelled = ContractEventLog<{
  _nftId: string;
  _price: string;
  _owner: string;
  _cancelledBy: string;
  _timestamp: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;
export type Sold = ContractEventLog<{
  _nftId: string;
  _seller: string;
  _buyer: string;
  _price: string;
  _timestamp: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;

export interface OATSaleImplementation extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): OATSaleImplementation;
  clone(): OATSaleImplementation;
  methods: {
    isActive(): NonPayableTransactionObject<boolean>;

    isTrustedForwarder(forwarder: string): NonPayableTransactionObject<boolean>;

    nftAddress(): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    trustedForwarder(): NonPayableTransactionObject<string>;

    initialize(
      _nftAddress: string,
      _trustedForwarder: string
    ): NonPayableTransactionObject<void>;

    setTrustedForwarder(
      newTrustedForwarder: string
    ): NonPayableTransactionObject<void>;

    setAdmin(
      admin: string,
      enabled: boolean
    ): NonPayableTransactionObject<void>;

    isAdmin(admin: string): NonPayableTransactionObject<boolean>;

    setContractStatus(_isActive: boolean): NonPayableTransactionObject<void>;

    sellArtwork(
      nftId: number | string | BN,
      price: number | string | BN,
      artist: string
    ): NonPayableTransactionObject<void>;

    sellMyArtwork(
      nftId: number | string | BN,
      price: number | string | BN
    ): NonPayableTransactionObject<void>;

    sellArtworkBatch(
      nftIds: (number | string | BN)[],
      prices: (number | string | BN)[],
      artist: string
    ): NonPayableTransactionObject<void>;

    sellMyArtworkBatch(
      nftIds: (number | string | BN)[],
      prices: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    getSale(nftId: number | string | BN): NonPayableTransactionObject<{
      0: string;
      1: string;
    }>;

    cancelSale(nftId: number | string | BN): NonPayableTransactionObject<void>;

    purchaseArtwork(
      nftId: number | string | BN
    ): PayableTransactionObject<void>;

    purchaseArtworkBatch(
      nftIds: (number | string | BN)[]
    ): PayableTransactionObject<void>;

    releaseArtwork(
      nftId: number | string | BN,
      buyer: string
    ): NonPayableTransactionObject<void>;
  };
  events: {
    AdminAccessSet(cb?: Callback<AdminAccessSet>): EventEmitter;
    AdminAccessSet(
      options?: EventOptions,
      cb?: Callback<AdminAccessSet>
    ): EventEmitter;

    ContractStatusSet(cb?: Callback<ContractStatusSet>): EventEmitter;
    ContractStatusSet(
      options?: EventOptions,
      cb?: Callback<ContractStatusSet>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    SaleAdded(cb?: Callback<SaleAdded>): EventEmitter;
    SaleAdded(options?: EventOptions, cb?: Callback<SaleAdded>): EventEmitter;

    SaleCancelled(cb?: Callback<SaleCancelled>): EventEmitter;
    SaleCancelled(
      options?: EventOptions,
      cb?: Callback<SaleCancelled>
    ): EventEmitter;

    Sold(cb?: Callback<Sold>): EventEmitter;
    Sold(options?: EventOptions, cb?: Callback<Sold>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "AdminAccessSet", cb: Callback<AdminAccessSet>): void;
  once(
    event: "AdminAccessSet",
    options: EventOptions,
    cb: Callback<AdminAccessSet>
  ): void;

  once(event: "ContractStatusSet", cb: Callback<ContractStatusSet>): void;
  once(
    event: "ContractStatusSet",
    options: EventOptions,
    cb: Callback<ContractStatusSet>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;

  once(event: "SaleAdded", cb: Callback<SaleAdded>): void;
  once(
    event: "SaleAdded",
    options: EventOptions,
    cb: Callback<SaleAdded>
  ): void;

  once(event: "SaleCancelled", cb: Callback<SaleCancelled>): void;
  once(
    event: "SaleCancelled",
    options: EventOptions,
    cb: Callback<SaleCancelled>
  ): void;

  once(event: "Sold", cb: Callback<Sold>): void;
  once(event: "Sold", options: EventOptions, cb: Callback<Sold>): void;
}
